### ISSUE TITLE
Build fails with go 1.7 on amd64

### ISSUE THREAD

**Issue by lucas-clemente** [aead/chacha20#1]
I think the latest merge broke the build with go 1.7 on amd64:

```
~/s/g/s/g/a/chacha20 git:(master) → go test .
# github.com/aead/chacha20/chacha
chacha/chacha.go:55: undefined: xorBlocks
chacha/chacha_amd64.go:30: undefined: xorBlocks
FAIL	github.com/aead/chacha20 [build failed]
~/s/g/s/g/a/chacha20 git:(master) → go version
go version go1.7rc3 darwin/amd64
```

Maybe you could setup a CI like travis to detect this in the future?

**Comment by aead** [comment]
Just seen it - disabled AVX2 as a quick fix.
Sry for this avoidable problem - CI is actually a must have as soon 
as some else relies on the code.
